name = "NonEquilibriumGreenFunction"
uuid = "23f16301-fe5b-45da-b088-f1dd23511803"
version = "0.2.0"
authors = ["Baptiste Lamic"]

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
HssMatrices = "0c1fde87-e0ea-49d6-ac2f-89b694f639e1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[compat]
FFTW = "1"
HssMatrices = "0.1"
LinearAlgebra = "1"
NNlib = "0.9"
SparseArrays = "1"
SpecialFunctions = "2"
Statistics = "1"
StatsBase = "0.34"
TestItems = "1"
julia = "1.10"
