name = "NonEquilibriumGreenFunction"
uuid = "23f16301-fe5b-45da-b088-f1dd23511803"
version = "0.2.0"
authors = ["Baptiste Lamic"]

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
HssMatrices = "0c1fde87-e0ea-49d6-ac2f-89b694f639e1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Moshi = "2e0e35c7-a2e4-4343-998d-7ef72827ed2d"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[compat]
FFTW = "1"
Moshi = "0.3.7"
Revise = "3.12.0"
Statistics = "1"
TestItems = "1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
